import { NextResponse } from "next/server"
import { requireDesignContext } from "@/design/server/auth"
import { designTemplates } from "@/design/server/design-catalog.generated"

// GET /api/design/design-templates
//
// Daemon shape (apps/daemon/src/routes/static-resource.ts):
// `{ designTemplates: SkillSummary[] }` — the list strips `body`/`dir` and adds
// `hasBody`. Data is served from the committed `design-catalog.generated.ts`
// snapshot of the bundled open-design catalog (generated by
// scripts/import-od-design-systems.ts); the SPA parses `json.designTemplates ?? []`.
export async function GET(req: Request) {
  const gate = await requireDesignContext(req)
  if (!gate.ok) return gate.response
  const list = designTemplates.map(({ body, ...rest }) => ({
    ...rest,
    hasBody: body.length > 0,
  }))
  return NextResponse.json({ designTemplates: list })
}
