"use client"

import { useState, useCallback, useMemo, useEffect } from "react"
import { createPortal } from "react-dom"
import {
  X,
  Copy,
  Download,
  Check,
  Code,
  Eye,
  Play,
  ChevronLeft,
  ChevronRight,
  Pencil,
  Save,
  Trash2,
  MoreHorizontal,
  RotateCcw,
  AlertTriangle,
  AlertCircle,
} from "@/lib/icons"
import { Maximize, Minimize } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { cn } from "@/lib/utils"
import type { Artifact } from "./types"
import { TYPE_SHORT_LABELS, getArtifactRegistryEntry } from "./registry"
import { ArtifactRenderer } from "./artifact-renderer"
import { StreamdownContent } from "../streamdown-content"

type ArtifactInput = Omit<Artifact, "version" | "previousVersions"> & {
  version?: number
  previousVersions?: Artifact["previousVersions"]
}

interface ArtifactPanelProps {
  artifact: Artifact
  onClose: () => void
  onUpdateArtifact?: (artifact: ArtifactInput) => void
  onDeleteArtifact?: (artifactId: string) => void
  onFixWithAI?: (artifactId: string, error: string) => void
  sessionId?: string
}

export function ArtifactPanel({
  artifact,
  onClose,
  onUpdateArtifact,
  onDeleteArtifact,
  onFixWithAI,
  sessionId,
}: ArtifactPanelProps) {
  const isCodeOnly = artifact.type === "application/code"
  const isRunnable = artifact.type === "application/python"
  // text/document hides the Code tab — the preview is the source of truth
  // (renders the same DOCX bytes the user downloads, so a separate source view
  // would just duplicate what's already in the tool call).
  const isTextDocument = artifact.type === "text/document"
  const [tab, setTab] = useState<"preview" | "code">(
    isCodeOnly ? "code" : "preview"
  )
  const [isEditing, setIsEditing] = useState(false)
  const [copied, setCopied] = useState(false)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const [viewingVersionIdx, setViewingVersionIdx] = useState<number | null>(
    null
  )

  // Edit state
  const [editContent, setEditContent] = useState("")
  const [isDirty, setIsDirty] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [saveError, setSaveError] = useState<string | null>(null)
  const [isDeleting, setIsDeleting] = useState(false)

  // text/document export state. Preview shares the same generated bytes as
  // the download. Two export options are surfaced — Markdown source + Word
  // (.docx). Users wanting PDF should open the .docx in Word and Save as PDF.
  const [isExporting, setIsExporting] = useState(false)
  const [exportError, setExportError] = useState<string | null>(null)

  const hasVersions = artifact.previousVersions.length > 0
  const totalVersions = artifact.version
  const currentViewVersion =
    viewingVersionIdx !== null ? viewingVersionIdx + 1 : totalVersions
  const evictedCount = artifact.evictedVersionCount ?? 0
  const isViewingHistorical = viewingVersionIdx !== null
  // RAG indexing status: undefined means "unknown" (legacy artifact, before
  // we tracked the field) and we don't render anything for it. `false`
  // means indexing was attempted and failed/skipped.
  const ragIndexingFailed = artifact.ragIndexed === false

  const displayArtifact = useMemo<Artifact>(() => {
    if (viewingVersionIdx === null) return artifact
    const ver = artifact.previousVersions[viewingVersionIdx]
    if (!ver) return artifact
    return { ...artifact, content: ver.content, title: ver.title }
  }, [artifact, viewingVersionIdx])

  // Initialize edit content when entering edit mode or artifact changes
  // Skip if a save is in progress to prevent overwriting the editor
  useEffect(() => {
    if (isEditing && !isSaving) {
      setEditContent(displayArtifact.content)
      setIsDirty(false)
      setSaveError(null)
    }
  }, [isEditing, displayArtifact.content, isSaving])

  // Reset version view to latest when artifact is updated externally
  useEffect(() => {
    setViewingVersionIdx(null)
  }, [artifact.version])

  // Exit edit mode when switching tabs
  useEffect(() => {
    setIsEditing(false)
  }, [tab])

  // Escape key exits fullscreen
  useEffect(() => {
    if (!isFullscreen) return
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") setIsFullscreen(false)
    }
    document.addEventListener("keydown", handler)
    return () => document.removeEventListener("keydown", handler)
  }, [isFullscreen])

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(displayArtifact.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [displayArtifact.content])

  const handleDownload = useCallback(async () => {
    // Clear any prior error from a previous attempt before retrying.
    setExportError(null)
    const ext = getExtension(displayArtifact)
    const filename = `${displayArtifact.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}${ext}`

    // For slides, generate a real PPTX file
    if (displayArtifact.type === "application/slides") {
      try {
        const { isJsonPresentation, parseLegacyMarkdown } = await import("@/lib/slides/parse-legacy")
        const { DEFAULT_THEME } = await import("@/lib/slides/types")
        const { generatePptx } = await import("@/lib/slides/generate-pptx")

        let presentation
        if (isJsonPresentation(displayArtifact.content)) {
          const parsed = JSON.parse(displayArtifact.content)
          presentation = { theme: parsed.theme || DEFAULT_THEME, slides: parsed.slides }
        } else {
          presentation = parseLegacyMarkdown(displayArtifact.content)
        }

        const blob = await generatePptx(presentation)
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = filename
        a.click()
        URL.revokeObjectURL(url)
      } catch (err) {
        const message = err instanceof Error ? err.message : "Unknown error"
        console.error("[ArtifactPanel] PPTX generation failed:", err)
        setExportError(`PPTX export failed: ${message}`)
      }
      return
    }

    // Spreadsheet JSON spec → real .xlsx via ExcelJS
    if (displayArtifact.type === "application/sheet") {
      const trimmed = displayArtifact.content.trimStart()
      if (trimmed.startsWith("{")) {
        try {
          const parsed = JSON.parse(trimmed)
          if (parsed?.kind === "spreadsheet/v1") {
            const { parseSpec } = await import("@/lib/spreadsheet/parse")
            const { evaluateWorkbook } = await import("@/lib/spreadsheet/formulas")
            const { generateXlsx } = await import("@/lib/spreadsheet/generate-xlsx")
            const result = parseSpec(displayArtifact.content)
            if (!result.ok || !result.spec) {
              console.error("[ArtifactPanel] Spreadsheet spec invalid:", result.errors)
              setExportError(`XLSX export failed: ${result.errors.join("; ") || "invalid spec"}`)
              return
            }
            const values = evaluateWorkbook(result.spec)
            const blob = await generateXlsx(result.spec, values)
            const url = URL.createObjectURL(blob)
            const a = document.createElement("a")
            a.href = url
            a.download = filename
            a.click()
            URL.revokeObjectURL(url)
            return
          }
        } catch (err) {
          const message = err instanceof Error ? err.message : "Unknown error"
          console.error("[ArtifactPanel] Spreadsheet download failed:", err)
          setExportError(`XLSX export failed: ${message}`)
          // fall through to CSV text path
        }
      }
    }

    // Historical versions archived to S3 (>32 KB) come back here without
    // their content loaded into the panel. Bail out with a user-visible
    // error rather than emitting a file that contains "undefined".
    if (typeof displayArtifact.content !== "string" || displayArtifact.content.length === 0) {
      setExportError(
        "Download isn't available for this version — its content was archived to storage and isn't loaded into the panel. Restore the version first, then download.",
      )
      return
    }

    // LaTeX artifacts are KaTeX fragments — they have no preamble and won't
    // compile in pdflatex as-is. Wrap them in a minimal article document on
    // download so users get a `.tex` file they can actually compile.
    const downloadContent =
      displayArtifact.type === "text/latex"
        ? wrapLatexForDownload(displayArtifact.content)
        : displayArtifact.content

    const blob = new Blob([downloadContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }, [displayArtifact])

  /**
   * Split-button download handler for text/document.
   *
   * - "md":   Blob from raw markdown content (baseline; no transformation).
   * - "docx": shares the same generated bytes the preview is rendering, so
   *           what the user sees is what they download (WYSIWYG by construction).
   *
   * PDF is intentionally not offered — open the .docx in Word and Save as PDF
   * for native typography. Per-format errors are caught into `exportError`;
   * the panel never crashes.
   */
  const handleDocumentDownload = useCallback(
    async (format: "md" | "docx") => {
      if (isExporting) return
      setExportError(null)
      const slug = displayArtifact.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()

      const triggerDownload = (blob: Blob, filename: string) => {
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = filename
        a.click()
        URL.revokeObjectURL(url)
      }

      try {
        if (format === "md") {
          // Historical versions stored only in S3 have `content === undefined`
          // here (only inline-fallback versions ≤ 32 KB carry their bytes in
          // metadata). Without this guard the user gets a `.md` containing
          // the literal string "undefined".
          if (typeof displayArtifact.content !== "string" || displayArtifact.content.length === 0) {
            setExportError(
              "Markdown download isn't available for this version — its content was archived to storage and isn't loaded into the panel. Restore the version first, then download.",
            )
            return
          }
          const blob = new Blob([displayArtifact.content], { type: "text/markdown" })
          triggerDownload(blob, `${slug}.md`)
          return
        }

        setIsExporting(true)

        if (format === "docx") {
          if (!sessionId) {
            throw new Error(
              "Session context missing; reload the page and retry the download."
            )
          }
          const res = await fetch(
            `/api/dashboard/chat/sessions/${sessionId}/artifacts/${displayArtifact.id}/download?format=docx`
          )
          if (!res.ok) {
            const payload = (await res.json().catch(() => null)) as
              | { error?: string }
              | null
            throw new Error(
              payload?.error ?? `Download failed (HTTP ${res.status})`
            )
          }
          const blob = await res.blob()
          triggerDownload(blob, `${slug}.docx`)
          return
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err)
        console.error(`[ArtifactPanel] ${format} export failed:`, err)
        setExportError(`${format.toUpperCase()} export failed: ${message}`)
      } finally {
        setIsExporting(false)
      }
    },
    [displayArtifact, isExporting, sessionId]
  )

  const goToPrevVersion = useCallback(() => {
    if (viewingVersionIdx === null) {
      setViewingVersionIdx(artifact.previousVersions.length - 1)
    } else if (viewingVersionIdx > 0) {
      setViewingVersionIdx(viewingVersionIdx - 1)
    }
  }, [viewingVersionIdx, artifact.previousVersions.length])

  const goToNextVersion = useCallback(() => {
    if (viewingVersionIdx !== null) {
      if (viewingVersionIdx < artifact.previousVersions.length - 1) {
        setViewingVersionIdx(viewingVersionIdx + 1)
      } else {
        setViewingVersionIdx(null)
      }
    }
  }, [viewingVersionIdx, artifact.previousVersions.length])

  const handleSave = useCallback(async () => {
    if (!editContent || !isDirty || isSaving) return
    setIsSaving(true)
    setSaveError(null)

    try {
      // If a sessionId is wired up we hit the REST endpoint FIRST so the
      // server-side validator gets a chance to reject the edit. We only
      // commit the in-memory update once the server accepts the content,
      // otherwise the panel would jump to a stale-but-valid state while
      // showing an error from the rejected save.
      if (sessionId) {
        const res = await fetch(
          `/api/dashboard/chat/sessions/${sessionId}/artifacts/${artifact.id}`,
          {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ content: editContent }),
          }
        )
        if (!res.ok) {
          const body = (await res.json().catch(() => ({}))) as { error?: string }
          setSaveError(
            body.error ||
              `Save failed with HTTP ${res.status}. Try again or fix the highlighted issues.`,
          )
          return
        }
      }

      if (onUpdateArtifact) {
        onUpdateArtifact({
          id: artifact.id,
          title: artifact.title,
          type: artifact.type,
          content: editContent,
          language: artifact.language,
        })
      }

      setIsDirty(false)
      setIsEditing(false)
    } catch (err) {
      console.error("[ArtifactPanel] Save error:", err)
      setSaveError(
        err instanceof Error
          ? err.message
          : "Save failed — check your network connection.",
      )
    } finally {
      setIsSaving(false)
    }
  }, [
    editContent,
    isDirty,
    isSaving,
    artifact,
    onUpdateArtifact,
    sessionId,
  ])

  /**
   * Restore the currently-viewed historical version as a brand-new edit.
   * Goes through the same `onUpdateArtifact` + PUT path as a manual save so
   * the restore itself is captured as a new entry in the version history.
   */
  const handleRestoreVersion = useCallback(async () => {
    if (viewingVersionIdx === null) return
    const ver = artifact.previousVersions[viewingVersionIdx]
    if (!ver) return
    if (isSaving) return
    setIsSaving(true)
    try {
      onUpdateArtifact?.({
        id: artifact.id,
        title: ver.title || artifact.title,
        type: artifact.type,
        content: ver.content,
        language: artifact.language,
      })
      if (sessionId) {
        await fetch(
          `/api/dashboard/chat/sessions/${sessionId}/artifacts/${artifact.id}`,
          {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              content: ver.content,
              title: ver.title || artifact.title,
            }),
          }
        )
      }
      setViewingVersionIdx(null)
    } catch (err) {
      console.error("[ArtifactPanel] Restore error:", err)
    } finally {
      setIsSaving(false)
    }
  }, [
    viewingVersionIdx,
    artifact,
    isSaving,
    onUpdateArtifact,
    sessionId,
  ])

  const handleDelete = useCallback(async () => {
    if (isDeleting) return
    setIsDeleting(true)

    try {
      if (sessionId) {
        await fetch(
          `/api/dashboard/chat/sessions/${sessionId}/artifacts/${artifact.id}`,
          { method: "DELETE" }
        )
      }
      onDeleteArtifact?.(artifact.id)
      onClose()
    } catch (err) {
      console.error("[ArtifactPanel] Delete error:", err)
    } finally {
      setIsDeleting(false)
    }
  }, [isDeleting, sessionId, artifact.id, onDeleteArtifact, onClose])

  const closeFullscreen = useCallback(() => {
    setIsFullscreen(false)
  }, [])

  const panelContent = (
    <div
      className={cn(
        "flex flex-col bg-background",
        isFullscreen ? "fixed inset-3 z-50 rounded-xl shadow-2xl border" : "h-full border-l"
      )}
    >
      {/* Header */}
      <div className="flex items-center justify-between gap-3 px-4 py-3.5 border-b border-border/50">
        {/* Title area */}
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <div className="min-w-0 flex-1">
            <h3 className="text-base font-semibold truncate">
              {displayArtifact.title}
            </h3>
          </div>
          <span className="text-xs text-muted-foreground bg-muted rounded-full px-2 py-0.5 shrink-0">
            {TYPE_SHORT_LABELS[artifact.type] || artifact.type}
            {artifact.language ? ` · ${artifact.language}` : ""}
          </span>

          {/* Version pill (inline in header) */}
          {hasVersions && (
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="flex items-center gap-0.5 tabular-nums text-xs text-muted-foreground bg-muted rounded-full px-1 py-0.5 shrink-0">
                  <button
                    type="button"
                    className="h-5 w-5 flex items-center justify-center rounded-full hover:bg-background/80 transition-colors disabled:opacity-30"
                    onClick={goToPrevVersion}
                    disabled={currentViewVersion <= 1}
                  >
                    <ChevronLeft className="h-3 w-3" />
                  </button>
                  <span className="px-0.5 font-medium">
                    {currentViewVersion}/{totalVersions}
                  </span>
                  <button
                    type="button"
                    className="h-5 w-5 flex items-center justify-center rounded-full hover:bg-background/80 transition-colors disabled:opacity-30"
                    onClick={goToNextVersion}
                    disabled={currentViewVersion >= totalVersions}
                  >
                    <ChevronRight className="h-3 w-3" />
                  </button>
                </span>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                {evictedCount > 0
                  ? `+${evictedCount} earlier version${evictedCount === 1 ? "" : "s"} evicted (cap is 20)`
                  : "Browse previous versions"}
              </TooltipContent>
            </Tooltip>
          )}

          {/* Restore-this-version button — only when viewing a historical
              version, and only if updates are wired up. */}
          {isViewingHistorical && onUpdateArtifact && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 px-2 text-xs gap-1 shrink-0"
                  onClick={handleRestoreVersion}
                  disabled={isSaving}
                >
                  <RotateCcw className="h-3 w-3" />
                  Restore
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                Replace the latest content with this historical version
                (creates a new version entry)
              </TooltipContent>
            </Tooltip>
          )}

          {/* RAG indexing status: only shown when explicitly false. */}
          {ragIndexingFailed && (
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="inline-flex items-center gap-1 text-[11px] text-amber-600 dark:text-amber-400 bg-amber-500/10 rounded-full px-1.5 py-0.5 shrink-0">
                  <AlertTriangle className="h-3 w-3" />
                  Not searchable
                </span>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                Background RAG indexing didn&apos;t complete for this artifact —
                it won&apos;t appear in semantic search results until it&apos;s
                re-indexed.
              </TooltipContent>
            </Tooltip>
          )}
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-0.5 shrink-0">
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8"
                onClick={handleCopy}
              >
                {copied ? (
                  <Check className="h-4 w-4 text-chart-2" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">Copy content</TooltipContent>
          </Tooltip>

          {displayArtifact.type === "text/document" ? (
            <DropdownMenu>
              <Tooltip>
                <TooltipTrigger asChild>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      disabled={isExporting}
                    >
                      <Download
                        className={cn(
                          "h-4 w-4",
                          isExporting && "animate-pulse"
                        )}
                      />
                    </Button>
                  </DropdownMenuTrigger>
                </TooltipTrigger>
                <TooltipContent side="bottom">
                  {isExporting ? "Generating..." : "Download as..."}
                </TooltipContent>
              </Tooltip>
              <DropdownMenuContent align="end">
                <DropdownMenuItem
                  onClick={() => handleDocumentDownload("md")}
                  disabled={isExporting}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download as Markdown (.md)
                </DropdownMenuItem>
                <DropdownMenuItem
                  onClick={() => handleDocumentDownload("docx")}
                  disabled={isExporting}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download as Word (.docx)
                </DropdownMenuItem>
                {exportError && (
                  <div className="px-2 py-1.5 text-xs text-destructive border-t mt-1">
                    {exportError}
                  </div>
                )}
              </DropdownMenuContent>
            </DropdownMenu>
          ) : (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={handleDownload}
                >
                  <Download className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">Download</TooltipContent>
            </Tooltip>
          )}

          {/* More menu (delete lives here) */}
          {onDeleteArtifact && (
            <DropdownMenu>
              <Tooltip>
                <TooltipTrigger asChild>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="icon" className="h-8 w-8">
                      <MoreHorizontal className="h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                </TooltipTrigger>
                <TooltipContent side="bottom">More options</TooltipContent>
              </Tooltip>
              <DropdownMenuContent align="end">
                <DropdownMenuItem
                  className="text-destructive focus:text-destructive"
                  onClick={handleDelete}
                  disabled={isDeleting}
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  {isDeleting ? "Deleting..." : "Delete artifact"}
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          )}

          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8"
                onClick={() => setIsFullscreen((prev) => !prev)}
              >
                {isFullscreen ? (
                  <Minimize className="h-4 w-4" />
                ) : (
                  <Maximize className="h-4 w-4" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">
              {isFullscreen ? "Exit fullscreen" : "Fullscreen"}
            </TooltipContent>
          </Tooltip>

          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8"
                onClick={() => {
                  if (isFullscreen) setIsFullscreen(false)
                  onClose()
                }}
              >
                <X className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">Close</TooltipContent>
          </Tooltip>
        </div>
      </div>

      {/* Export-error banner for non-document downloads (PPTX, XLSX, etc.).
          Document downloads have their own dropdown-scoped error display.
          Banner is dismissed automatically on the next download attempt. */}
      {exportError && !isTextDocument && (
        <div className="flex items-start gap-2 px-4 py-2 text-xs text-destructive bg-destructive/10 border-b border-destructive/30">
          <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
          <div className="flex-1">{exportError}</div>
          <button
            type="button"
            className="text-muted-foreground hover:text-foreground"
            onClick={() => setExportError(null)}
            aria-label="Dismiss error"
          >
            <X className="h-3.5 w-3.5" />
          </button>
        </div>
      )}

      {/* Tab bar — hidden for application/code (preview == code, redundant)
          and for text/document (preview is the source of truth for exports;
          a separate Code tab would mislead users into thinking they can edit
          the .docx directly from there). */}
      {!isCodeOnly && !isTextDocument && (
      <div className="flex border-b border-border/50 px-4">
        <button
          type="button"
          className={cn(
            "flex items-center gap-1.5 px-3 py-2.5 text-sm font-medium border-b-2 transition-colors",
            tab === "preview"
              ? "border-primary text-foreground"
              : "border-transparent text-muted-foreground hover:text-foreground"
          )}
          onClick={() => setTab("preview")}
        >
          {isRunnable ? <Play className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}
          {isRunnable ? "Run" : "Preview"}
        </button>
        <button
          type="button"
          className={cn(
            "flex items-center gap-1.5 px-3 py-2.5 text-sm font-medium border-b-2 transition-colors",
            tab === "code"
              ? "border-primary text-foreground"
              : "border-transparent text-muted-foreground hover:text-foreground"
          )}
          onClick={() => setTab("code")}
        >
          <Code className="h-3.5 w-3.5" />
          Code
          {isDirty && isEditing && (
            <span className="w-1.5 h-1.5 rounded-full bg-chart-1" />
          )}
        </button>
      </div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-auto">
        {tab === "preview" || isTextDocument ? (
          <ArtifactRenderer
            artifact={displayArtifact}
            onFixWithAI={onFixWithAI ? (error: string) => onFixWithAI(displayArtifact.id, error) : undefined}
            onDownloadXlsx={handleDownload}
          />
        ) : isEditing ? (
          /* Code tab — edit mode */
          <div className="flex flex-col h-full">
            <textarea
              value={editContent}
              onChange={(e) => {
                setEditContent(e.target.value)
                setIsDirty(true)
                if (saveError) setSaveError(null)
              }}
              className="flex-1 w-full p-4 font-mono text-sm bg-background text-foreground resize-none outline-none"
              spellCheck={false}
            />
            {saveError && (
              <div className="px-4 py-2 border-t bg-amber-500/5 text-xs text-amber-600 dark:text-amber-400 whitespace-pre-wrap">
                <div className="flex items-center gap-1.5 font-medium mb-1">
                  <AlertTriangle className="h-3.5 w-3.5" />
                  Save rejected
                </div>
                {saveError}
              </div>
            )}
            <div className="flex items-center justify-end gap-2 px-4 py-2 border-t bg-muted/30">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setEditContent(displayArtifact.content)
                  setIsDirty(false)
                  setIsEditing(false)
                }}
              >
                Cancel
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setEditContent(displayArtifact.content)
                  setIsDirty(false)
                }}
                disabled={!isDirty}
              >
                Discard
              </Button>
              <Button
                size="sm"
                onClick={handleSave}
                disabled={!isDirty || isSaving}
              >
                <Save className="h-3.5 w-3.5 mr-1.5" />
                {isSaving ? "Saving..." : "Save"}
              </Button>
            </div>
          </div>
        ) : (
          /* Code tab — view mode with floating edit button */
          <div className="relative">
            <StreamdownContent
              content={`\`\`\`${getCodeLanguage(displayArtifact)}\n${displayArtifact.content}\n\`\`\``}
              className="p-4"
            />
            {onUpdateArtifact && (
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="secondary"
                    size="icon"
                    className="absolute top-3 right-3 h-8 w-8 shadow-sm"
                    onClick={() => setIsEditing(true)}
                  >
                    <Pencil className="h-3.5 w-3.5" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="left">Edit code</TooltipContent>
              </Tooltip>
            )}
          </div>
        )}
      </div>
    </div>
  )

  // When fullscreen, render via portal with backdrop. The early return
  // here guarantees that whenever `isFullscreen === true` we go through
  // the portal branch — there is exactly one render path for fullscreen,
  // so the embedded `panelContent` JSX will never be mounted twice (once
  // inline + once portaled) and the backdrop is always present.
  if (isFullscreen) {
    return createPortal(
      <>
        <div
          className="fixed inset-0 z-40 bg-black/50"
          onClick={closeFullscreen}
        />
        {panelContent}
      </>,
      document.body
    )
  }

  return panelContent
}

/**
 * Map a Shiki/canonical language identifier to a conventional file
 * extension. Without this, an `application/code` artifact tagged
 * `typescript` would download as `foo.typescript` instead of `foo.ts`.
 *
 * The keys here mirror the Shiki language list the prompts ask the LLM to
 * use; entries not in the table fall back to the language string itself
 * (so a niche/new language still produces a recognizable filename).
 */
const CODE_LANGUAGE_EXTENSIONS: Record<string, string> = {
  typescript: "ts",
  javascript: "js",
  tsx: "tsx",
  jsx: "jsx",
  python: "py",
  ruby: "rb",
  rust: "rs",
  go: "go",
  java: "java",
  kotlin: "kt",
  swift: "swift",
  csharp: "cs",
  cpp: "cpp",
  c: "c",
  php: "php",
  shell: "sh",
  bash: "sh",
  zsh: "sh",
  sql: "sql",
  html: "html",
  css: "css",
  scss: "scss",
  json: "json",
  yaml: "yml",
  yml: "yml",
  toml: "toml",
  xml: "xml",
  markdown: "md",
  dockerfile: "dockerfile",
  makefile: "mk",
  perl: "pl",
  lua: "lua",
  r: "r",
  julia: "jl",
  haskell: "hs",
  elixir: "ex",
  erlang: "erl",
  scala: "scala",
  dart: "dart",
  graphql: "graphql",
  prisma: "prisma",
}

function codeExtension(language: string | undefined): string {
  if (!language) return ".txt"
  const key = language.toLowerCase().trim()
  const mapped = CODE_LANGUAGE_EXTENSIONS[key]
  return mapped ? `.${mapped}` : `.${key}`
}

function getExtension(artifact: Artifact): string {
  if (artifact.type === "application/code") return codeExtension(artifact.language)
  if (artifact.type === "application/sheet") {
    try {
      const trimmed = artifact.content.trimStart()
      if (trimmed.startsWith("{")) {
        const parsed = JSON.parse(trimmed)
        if (parsed?.kind === "spreadsheet/v1") return ".xlsx"
      }
    } catch {
      // fall through to csv
    }
    return ".csv"
  }
  return getArtifactRegistryEntry(artifact.type)?.extension ?? ".txt"
}

/**
 * Wrap a KaTeX fragment in a minimal article preamble so the downloaded
 * `.tex` file can compile in pdflatex / LuaTeX. The preamble loads the
 * packages KaTeX-supported commands typically need (`amsmath`, `amssymb`,
 * `amsthm`, `hyperref`). If the artifact already contains a `\documentclass`
 * line we leave it alone — the user wrote a full document themselves.
 */
function wrapLatexForDownload(body: string): string {
  if (/\\documentclass\b/.test(body)) return body
  return `\\documentclass{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{amsthm}
\\usepackage{hyperref}

\\begin{document}

${body.trim()}

\\end{document}
`
}

function getCodeLanguage(artifact: Artifact): string {
  if (artifact.type === "application/code") return artifact.language || ""
  return getArtifactRegistryEntry(artifact.type)?.codeLanguage ?? ""
}