import { NextResponse } from "next/server"
import { requireDesignContext } from "@/design/server/auth"
import { designSystems } from "@/design/server/design-catalog.generated"

// GET /api/design/design-systems
//
// Daemon shape (apps/daemon/src/routes/static-resource.ts):
// `{ designSystems: DesignSystemSummary[] }` — the list strips `body` (and, in
// our port, `packageInfo`). Data is served from the committed
// `design-catalog.generated.ts` snapshot of the bundled open-design catalog
// (generated by scripts/import-od-design-systems.ts); the SPA parses
// `json.designSystems ?? []`.
export async function GET(req: Request) {
  const gate = await requireDesignContext(req)
  if (!gate.ok) return gate.response
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const list = designSystems.map(({ body, packageInfo, ...summary }) => summary)
  return NextResponse.json({ designSystems: list })
}
