import {
  Zap,
  Webhook,
  Clock,
  Radio,
  Bot,
  Sparkles,
  Wrench,
  Plug,
  Code,
  Globe,
  GitFork,
  ArrowRightLeft,
  Repeat,
  GitBranch,
  Merge,
  UserCheck,
  HandHelping,
  Shuffle,
  Filter,
  Layers,
  Search,
  Database,
  HardDrive,
  Airplay,
  ShieldAlert,
  Workflow,
  Braces,
  type LucideIcon,
} from "lucide-react"
import { NodeType } from "@/lib/workflow/types"

export const NODE_ICON_MAP: Record<string, LucideIcon> = {
  [NodeType.TRIGGER_MANUAL]: Zap,
  [NodeType.TRIGGER_WEBHOOK]: Webhook,
  [NodeType.TRIGGER_SCHEDULE]: Clock,
  [NodeType.TRIGGER_EVENT]: Radio,
  [NodeType.AGENT]: Bot,
  [NodeType.LLM]: Sparkles,
  [NodeType.TOOL]: Wrench,
  [NodeType.MCP_TOOL]: Plug,
  [NodeType.CODE]: Code,
  [NodeType.HTTP]: Globe,
  [NodeType.CONDITION]: GitFork,
  [NodeType.SWITCH]: ArrowRightLeft,
  [NodeType.LOOP]: Repeat,
  [NodeType.PARALLEL]: GitBranch,
  [NodeType.MERGE]: Merge,
  [NodeType.HUMAN_INPUT]: UserCheck,
  [NodeType.APPROVAL]: HandHelping,
  [NodeType.HANDOFF]: ArrowRightLeft,
  [NodeType.TRANSFORM]: Shuffle,
  [NodeType.FILTER]: Filter,
  [NodeType.AGGREGATE]: Layers,
  [NodeType.OUTPUT_PARSER]: Braces,
  [NodeType.RAG_SEARCH]: Search,
  [NodeType.DATABASE]: Database,
  [NodeType.STORAGE]: HardDrive,
  [NodeType.ERROR_HANDLER]: ShieldAlert,
  [NodeType.SUB_WORKFLOW]: Workflow,
  [NodeType.STREAM_OUTPUT]: Airplay,
}
