/**
 * Seed the CatalogItem table with the static marketplace catalog.
 * Run: npx tsx scripts/seed-catalog.ts
 */
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

interface CatalogEntry {
  id: string
  name: string
  displayName: string
  description: string
  category: string
  type: "tool" | "skill"
  icon: string
  tags: string[]
  skillContent?: string
  skillCategory?: string
  toolTemplate?: object
}

// Inline the static catalog data for seed (avoids @/ path alias issues)
const ITEMS: CatalogEntry[] = [
  { id: "mp-google-calendar", name: "google-calendar", displayName: "Google Calendar", description: "Create, list, and manage calendar events", category: "Productivity", type: "tool", icon: "Calendar", tags: ["google", "calendar", "scheduling"], toolTemplate: { name: "google_calendar", displayName: "Google Calendar", description: "Manage Google Calendar events: create, list, update, and delete events", parameters: { type: "object", properties: { action: { type: "string", enum: ["list", "create", "update", "delete"] }, title: { type: "string" }, startTime: { type: "string" }, endTime: { type: "string" }, eventId: { type: "string" } } }, executionConfig: { url: "https://www.googleapis.com/calendar/v3/calendars/primary/events", method: "POST" } } },
  { id: "mp-notion", name: "notion", displayName: "Notion", description: "Search, create, and update Notion pages and databases", category: "Productivity", type: "tool", icon: "BookOpen", tags: ["notion", "notes", "wiki"], toolTemplate: { name: "notion_api", displayName: "Notion", description: "Search and manage Notion pages and databases", parameters: { type: "object", properties: { action: { type: "string", enum: ["search", "create_page", "update_page"] }, query: { type: "string" }, content: { type: "string" } } }, executionConfig: { url: "https://api.notion.com/v1/search", method: "POST" } } },
  { id: "mp-todoist", name: "todoist", displayName: "Todoist", description: "Manage tasks and projects in Todoist", category: "Productivity", type: "tool", icon: "CheckSquare", tags: ["tasks", "todo", "productivity"], toolTemplate: { name: "todoist", displayName: "Todoist", description: "Create, list, and complete tasks in Todoist", parameters: { type: "object", properties: { action: { type: "string", enum: ["list", "create", "complete", "delete"] }, content: { type: "string" }, projectId: { type: "string" } } }, executionConfig: { url: "https://api.todoist.com/rest/v2/tasks", method: "POST" } } },
  { id: "mp-time-management-skill", name: "time-management", displayName: "Time Management", description: "Teach the agent time management and scheduling strategies", category: "Productivity", type: "skill", icon: "Clock", tags: ["productivity", "planning", "time"], skillContent: "## Time Management Skill\n\nWhen the user asks about scheduling, planning, or time management:\n\n1. **Prioritize tasks** using the Eisenhower Matrix (urgent/important)\n2. **Suggest time blocks** for focused work (25-minute Pomodoro sessions)\n3. **Identify time wasters** and suggest alternatives\n4. **Create daily plans** with realistic time estimates\n5. **Recommend breaks** to maintain productivity\n\nAlways ask about deadlines and dependencies before creating a schedule.", skillCategory: "productivity" },
  { id: "mp-github-issues", name: "github-issues", displayName: "GitHub Issues", description: "Create, search, and manage GitHub issues", category: "Development", type: "tool", icon: "Github", tags: ["github", "issues", "development"], toolTemplate: { name: "github_issues", displayName: "GitHub Issues", description: "Manage GitHub issues: create, search, list, and comment", parameters: { type: "object", properties: { action: { type: "string", enum: ["list", "create", "comment", "close"] }, repo: { type: "string" }, title: { type: "string" }, body: { type: "string" } } }, executionConfig: { url: "https://api.github.com/repos/{owner}/{repo}/issues", method: "POST" } } },
  { id: "mp-jira", name: "jira", displayName: "Jira", description: "Create and manage Jira tickets", category: "Development", type: "tool", icon: "Ticket", tags: ["jira", "tickets", "project-management"], toolTemplate: { name: "jira_api", displayName: "Jira", description: "Create, search, and update Jira issues", parameters: { type: "object", properties: { action: { type: "string", enum: ["search", "create", "update", "transition"] }, projectKey: { type: "string" }, summary: { type: "string" }, description: { type: "string" } } }, executionConfig: { url: "https://your-domain.atlassian.net/rest/api/3/issue", method: "POST" } } },
  { id: "mp-linear", name: "linear", displayName: "Linear", description: "Manage Linear issues and projects", category: "Development", type: "tool", icon: "Layers", tags: ["linear", "issues", "project-management"], toolTemplate: { name: "linear_api", displayName: "Linear", description: "Create and manage Linear issues", parameters: { type: "object", properties: { action: { type: "string", enum: ["list", "create", "update"] }, title: { type: "string" }, description: { type: "string" }, teamId: { type: "string" } } }, executionConfig: { url: "https://api.linear.app/graphql", method: "POST" } } },
  { id: "mp-code-review-skill", name: "code-review", displayName: "Code Review", description: "Teach the agent thorough code review practices", category: "Development", type: "skill", icon: "Code", tags: ["code-review", "development", "quality"], skillContent: "## Code Review Skill\n\nWhen reviewing code, follow this systematic approach:\n\n### Security\n- Check for injection vulnerabilities (SQL, XSS, command)\n- Verify input validation and sanitization\n- Check for hardcoded secrets or credentials\n\n### Quality\n- Verify error handling covers edge cases\n- Check for proper null/undefined handling\n- Ensure consistent naming conventions\n- Look for code duplication that should be abstracted\n\n### Performance\n- Identify N+1 query patterns\n- Check for unnecessary re-renders (React)\n- Verify proper use of indexes for DB queries\n\n### Maintainability\n- Ensure functions have single responsibility\n- Check for proper typing (TypeScript)\n- Verify tests cover critical paths\n\nProvide specific line references and suggest concrete fixes.", skillCategory: "coding" },
  { id: "mp-git-workflow-skill", name: "git-workflow", displayName: "Git Workflow", description: "Guide users through Git branching and PR workflows", category: "Development", type: "skill", icon: "GitBranch", tags: ["git", "workflow", "branching"], skillContent: "## Git Workflow Skill\n\nGuide users through Git best practices:\n\n### Branch Naming\n- `feature/` — new features\n- `fix/` — bug fixes\n- `chore/` — maintenance tasks\n- `docs/` — documentation updates\n\n### Commit Messages\nFollow Conventional Commits: `type(scope): description`\n- feat, fix, chore, docs, refactor, test, style\n\n### PR Workflow\n1. Create feature branch from main\n2. Make atomic commits with clear messages\n3. Write PR description with context and test plan\n4. Request review from relevant team members\n5. Address feedback, squash if needed\n6. Merge via squash-and-merge\n\n### Conflict Resolution\n- Always rebase on latest main before merging\n- Resolve conflicts locally, test before pushing", skillCategory: "coding" },
  { id: "mp-slack", name: "slack", displayName: "Slack", description: "Send messages and manage Slack channels", category: "Communication", type: "tool", icon: "MessageSquare", tags: ["slack", "messaging", "team"], toolTemplate: { name: "slack_api", displayName: "Slack", description: "Send messages and interact with Slack channels", parameters: { type: "object", properties: { action: { type: "string", enum: ["send_message", "list_channels", "search"] }, channel: { type: "string" }, text: { type: "string" } } }, executionConfig: { url: "https://slack.com/api/chat.postMessage", method: "POST" } } },
  { id: "mp-discord", name: "discord", displayName: "Discord", description: "Send messages to Discord channels via webhooks", category: "Communication", type: "tool", icon: "Headphones", tags: ["discord", "messaging", "community"], toolTemplate: { name: "discord_webhook", displayName: "Discord", description: "Send messages to Discord channels", parameters: { type: "object", properties: { content: { type: "string" }, username: { type: "string" } } }, executionConfig: { url: "https://discord.com/api/webhooks/{webhook_id}/{webhook_token}", method: "POST" } } },
  { id: "mp-email-drafter-skill", name: "email-drafter", displayName: "Email Drafter", description: "Craft professional emails with proper tone and structure", category: "Communication", type: "skill", icon: "Mail", tags: ["email", "writing", "professional"], skillContent: "## Email Drafter Skill\n\nWhen drafting emails:\n\n### Structure\n1. **Subject line**: Clear, specific, actionable (under 60 chars)\n2. **Greeting**: Match formality to relationship\n3. **Opening**: State purpose in first sentence\n4. **Body**: One idea per paragraph, use bullet points for lists\n5. **CTA**: Clear next step or request\n6. **Closing**: Professional sign-off appropriate to context\n\n### Tone Guidelines\n- **Formal**: Executive communication, external clients, first contact\n- **Professional**: Team updates, cross-department, vendors\n- **Casual**: Close colleagues, internal quick updates\n\n### Rules\n- Keep under 200 words when possible\n- Highlight deadlines and action items\n- Proofread for grammar and typos\n- Ask about recipient and context before drafting", skillCategory: "communication" },
  { id: "mp-google-sheets", name: "google-sheets", displayName: "Google Sheets", description: "Read and write data to Google Sheets", category: "Data", type: "tool", icon: "Table", tags: ["google", "sheets", "spreadsheet"], toolTemplate: { name: "google_sheets", displayName: "Google Sheets", description: "Read and write data to Google Sheets spreadsheets", parameters: { type: "object", properties: { action: { type: "string", enum: ["read", "write", "append"] }, spreadsheetId: { type: "string" }, range: { type: "string" }, values: { type: "array" } } }, executionConfig: { url: "https://sheets.googleapis.com/v4/spreadsheets", method: "POST" } } },
  { id: "mp-airtable", name: "airtable", displayName: "Airtable", description: "Query and update Airtable bases", category: "Data", type: "tool", icon: "Database", tags: ["airtable", "database", "spreadsheet"], toolTemplate: { name: "airtable_api", displayName: "Airtable", description: "Query, create, and update records in Airtable", parameters: { type: "object", properties: { action: { type: "string", enum: ["list", "create", "update", "delete"] }, baseId: { type: "string" }, tableName: { type: "string" }, fields: { type: "object" } } }, executionConfig: { url: "https://api.airtable.com/v0/{baseId}/{tableName}", method: "POST" } } },
  { id: "mp-data-analysis-skill", name: "data-analysis", displayName: "Data Analysis", description: "Guide structured data analysis and visualization recommendations", category: "Data", type: "skill", icon: "BarChart", tags: ["data", "analysis", "statistics"], skillContent: "## Data Analysis Skill\n\nWhen analyzing data:\n\n### Approach\n1. **Understand the question** — What business decision does this inform?\n2. **Explore the data** — Check shape, types, missing values, distributions\n3. **Clean and prepare** — Handle nulls, outliers, type conversions\n4. **Analyze** — Apply appropriate statistical methods\n5. **Visualize** — Choose the right chart type\n6. **Interpret** — Explain findings in business context\n\n### Chart Selection\n- **Comparison**: Bar chart, grouped bar\n- **Trend over time**: Line chart\n- **Distribution**: Histogram, box plot\n- **Composition**: Pie/donut (max 5 slices), stacked bar\n- **Correlation**: Scatter plot\n\n### Best Practices\n- Always state sample size and time range\n- Note limitations and potential biases\n- Provide confidence intervals when appropriate\n- Suggest follow-up analyses", skillCategory: "data" },
  { id: "mp-technical-writer-skill", name: "technical-writer", displayName: "Technical Writer", description: "Write clear technical documentation and API docs", category: "AI & Writing", type: "skill", icon: "FileText", tags: ["documentation", "technical-writing", "api-docs"], skillContent: "## Technical Writer Skill\n\nWhen writing technical documentation:\n\n### Structure\n- **Overview**: What it does, who it's for, prerequisites\n- **Quick Start**: Get running in under 5 minutes\n- **API Reference**: Every endpoint/function documented\n- **Examples**: Real-world usage with copy-paste code\n- **Troubleshooting**: Common issues and solutions\n\n### Style\n- Use active voice (\"Send a request\" not \"A request should be sent\")\n- One sentence per line in source (better diffs)\n- Code examples must be complete and runnable\n- Use consistent terminology (define terms in glossary)\n\n### API Documentation\n- Method, path, description\n- Request body with types and examples\n- Response body with status codes\n- Error responses\n- Rate limits and authentication", skillCategory: "writing" },
  { id: "mp-content-strategist-skill", name: "content-strategist", displayName: "Content Strategist", description: "Plan and structure content for marketing and SEO", category: "AI & Writing", type: "skill", icon: "PenTool", tags: ["content", "marketing", "seo"], skillContent: "## Content Strategist Skill\n\nWhen creating content:\n\n### SEO Basics\n- Include primary keyword in title, H1, first paragraph\n- Use semantic keywords naturally throughout\n- Write meta descriptions (150-160 chars)\n- Structure with H2/H3 headings\n\n### Content Types\n- **Blog posts**: 1500-2500 words, scannable, actionable\n- **Landing pages**: Clear value prop, social proof, CTA\n- **Social posts**: Platform-specific length and tone\n- **Email sequences**: Nurture leads with increasing value\n\n### Writing Frameworks\n- **AIDA**: Attention, Interest, Desire, Action\n- **PAS**: Problem, Agitate, Solution\n- **Before/After/Bridge**: Show transformation\n\nAlways ask about target audience, goals, and brand voice before writing.", skillCategory: "writing" },
  { id: "mp-translator-skill", name: "translator", displayName: "Translator", description: "High-quality translation with cultural context", category: "AI & Writing", type: "skill", icon: "Languages", tags: ["translation", "multilingual", "localization"], skillContent: "## Translator Skill\n\nWhen translating:\n\n### Principles\n1. **Meaning first**: Convey the intent, not word-for-word\n2. **Cultural adaptation**: Adjust idioms, references, humor\n3. **Register matching**: Keep the same formality level\n4. **Consistency**: Use the same terms throughout\n\n### Process\n1. Identify source language (ask if unclear)\n2. Understand context and purpose\n3. Translate with natural target language phrasing\n4. Provide alternatives for ambiguous terms\n5. Note cultural differences that affect meaning\n\n### Format\n- Provide translation with original for reference\n- Mark uncertain translations with [?]\n- Explain cultural nuances in notes\n- For technical terms, provide both translated and original", skillCategory: "writing" },
  { id: "mp-zendesk", name: "zendesk", displayName: "Zendesk", description: "Create and manage Zendesk support tickets", category: "Customer Support", type: "tool", icon: "HeadphonesIcon", tags: ["zendesk", "support", "tickets"], toolTemplate: { name: "zendesk_api", displayName: "Zendesk", description: "Create, search, and update Zendesk support tickets", parameters: { type: "object", properties: { action: { type: "string", enum: ["create", "search", "update", "comment"] }, subject: { type: "string" }, description: { type: "string" }, ticketId: { type: "string" } } }, executionConfig: { url: "https://your-domain.zendesk.com/api/v2/tickets", method: "POST" } } },
  { id: "mp-customer-empathy-skill", name: "customer-empathy", displayName: "Customer Empathy", description: "Handle customer interactions with empathy and professionalism", category: "Customer Support", type: "skill", icon: "Heart", tags: ["customer-service", "empathy", "support"], skillContent: "## Customer Empathy Skill\n\nWhen interacting with customers:\n\n### Response Framework (HEAR)\n1. **Hear**: Acknowledge the specific issue\n2. **Empathize**: Show understanding of their frustration\n3. **Apologize**: Take responsibility where appropriate\n4. **Resolve**: Provide clear next steps\n\n### Tone Rules\n- Never blame the customer\n- Avoid jargon and technical terms\n- Use \"I\" and \"we\" (not \"the system\" or \"the policy\")\n- Match urgency to the customer's emotional state\n\n### De-escalation\n- Validate their feelings first\n- Offer options, not ultimatums\n- Set realistic expectations for resolution time\n- Follow up on promises made\n\n### Angry Customer Template\n\"I understand how frustrating [specific issue] must be. I'm sorry you're experiencing this. Let me [specific action] right away. Here's what will happen next: [clear timeline].\"", skillCategory: "support" },
  { id: "mp-weather", name: "weather", displayName: "Weather API", description: "Get current weather and forecasts for any location", category: "Utilities", type: "tool", icon: "Cloud", tags: ["weather", "forecast", "location"], toolTemplate: { name: "weather_api", displayName: "Weather API", description: "Get current weather and forecasts for any location", parameters: { type: "object", properties: { location: { type: "string", description: "City name or coordinates" }, units: { type: "string", enum: ["metric", "imperial"], description: "Temperature units" } }, required: ["location"] }, executionConfig: { url: "https://api.openweathermap.org/data/2.5/weather", method: "GET" } } },
  { id: "mp-qr-code", name: "qr-code", displayName: "QR Code Generator", description: "Generate QR codes from text or URLs", category: "Utilities", type: "tool", icon: "QrCode", tags: ["qr-code", "generator", "utility"], toolTemplate: { name: "qr_code_generator", displayName: "QR Code Generator", description: "Generate QR codes from text, URLs, or data", parameters: { type: "object", properties: { data: { type: "string", description: "Text or URL to encode" }, size: { type: "number", description: "Image size in pixels" } }, required: ["data"] }, executionConfig: { url: "https://api.qrserver.com/v1/create-qr-code/", method: "GET" } } },
]

async function main() {
  console.log("=== Seed Marketplace Catalog ===\n")

  for (const item of ITEMS) {
    await prisma.catalogItem.upsert({
      where: { id: item.id },
      update: {
        displayName: item.displayName,
        description: item.description,
        category: item.category,
        type: item.type,
        icon: item.icon,
        tags: item.tags,
        skillContent: item.skillContent || null,
        skillCategory: item.skillCategory || null,
        toolTemplate: item.toolTemplate || null,
      },
      create: {
        id: item.id,
        name: item.name,
        displayName: item.displayName,
        description: item.description,
        category: item.category,
        type: item.type,
        icon: item.icon,
        tags: item.tags,
        skillContent: item.skillContent || null,
        skillCategory: item.skillCategory || null,
        toolTemplate: item.toolTemplate || null,
      },
    })
    console.log(`  ${item.displayName}`)
  }

  console.log(`\nSeeded ${ITEMS.length} catalog items`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
