use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use super::generate_random_string;
use crate::app::InstallConfig;

/// Generate the .env file from the install configuration.
/// Auto-generates random values for any secrets left empty.
pub fn generate_config(config: &mut InstallConfig) -> Result<(), String> {
    // Auto-fill empty secrets
    if config.db_password.is_empty() {
        config.db_password = generate_random_string(16);
    }
    if config.nextauth_secret.is_empty() {
        config.nextauth_secret = generate_random_string(32);
    }
    if config.s3_access_key.is_empty() {
        config.s3_access_key = generate_random_string(20);
    }
    if config.s3_secret_key.is_empty() {
        config.s3_secret_key = generate_random_string(40);
    }
    if config.admin_password.is_empty() {
        config.admin_password = generate_random_string(16);
    }
    if config.surrealdb_pass.is_empty() {
        config.surrealdb_pass = generate_random_string(16);
    }

    let database_url = format!(
        "postgresql://{}:{}@{}:{}/{}",
        config.db_user, config.db_password, config.db_host, config.db_port, config.db_name,
    );

    let env_content = format!(
        r#"# ─────────────────────────────────────────────────────────
# RantAI Agents — Environment Configuration
# Generated by rantai-agents-installer
# ─────────────────────────────────────────────────────────

# ── PostgreSQL ──
DATABASE_URL="{database_url}"
DB_HOST={db_host}
DB_PORT={db_port}
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}

# ── SurrealDB (Vector Store) ──
VECTOR_DB_URL={surrealdb_url}
SURREALDB_USER={surrealdb_user}
SURREALDB_PASS={surrealdb_pass}

# ── S3 Storage (RustFS) ──
S3_ENDPOINT={s3_endpoint}
S3_ACCESS_KEY={s3_access_key}
S3_SECRET_KEY={s3_secret_key}
S3_BUCKET={s3_bucket}
S3_REGION=us-east-1

# ── Authentication ──
NEXTAUTH_SECRET={nextauth_secret}
NEXTAUTH_URL={nextauth_url}

# ── LLM Provider ──
OPENROUTER_API_KEY={openrouter_api_key}

# ── OCR (Ollama) ──
OCR_PROVIDER=ollama
OCR_MODEL=glm-ocr
OCR_API_URL={ollama_url}

# ── Code Interpreter (Piston) ──
CODE_INTERPRETER_URL={piston_url}
CODE_INTERPRETER_ENABLED={piston_enabled}

# ── Web Search (SearXNG) ──
SEARCH_API_URL={searxng_url}
SEARCH_API_ENABLED={searxng_enabled}

# ── Admin ──
ADMIN_EMAIL={admin_email}
ADMIN_PASSWORD={admin_password}

# ── Runtime ──
NODE_ENV=production
PORT=3000
"#,
        database_url = database_url,
        db_host = config.db_host,
        db_port = config.db_port,
        db_name = config.db_name,
        db_user = config.db_user,
        db_password = config.db_password,
        surrealdb_url = config.surrealdb_url,
        surrealdb_user = config.surrealdb_user,
        surrealdb_pass = config.surrealdb_pass,
        s3_endpoint = config.s3_endpoint,
        s3_access_key = config.s3_access_key,
        s3_secret_key = config.s3_secret_key,
        s3_bucket = config.s3_bucket,
        nextauth_secret = config.nextauth_secret,
        nextauth_url = config.nextauth_url,
        openrouter_api_key = config.openrouter_api_key,
        ollama_url = config.ollama_url,
        piston_url = config.piston_url,
        piston_enabled = config.enable_piston,
        searxng_url = config.searxng_url,
        searxng_enabled = config.enable_searxng,
        admin_email = config.admin_email,
        admin_password = config.admin_password,
    );

    let env_path = format!("{}/.env", config.install_dir);

    // Ensure install dir exists
    if let Some(parent) = Path::new(&env_path).parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create install directory: {}", e))?;
    }

    fs::write(&env_path, env_content).map_err(|e| format!("Failed to write .env file: {}", e))?;

    // Set restrictive permissions (owner read/write only)
    fs::set_permissions(&env_path, fs::Permissions::from_mode(0o600))
        .map_err(|e| format!("Failed to set .env permissions: {}", e))?;

    Ok(())
}
