import type { DocumentAst } from "@/lib/document-ast/schema"

/**
 * Golden fixture: Empirical Performance of NQRust-HV vs Java Monolith Migrations
 * Author: Dr. Aryan Kusuma (R&D Team Lead, NQ Technology)
 * Date: 2026-03-15  (pre-dates the proposal fixture at 2026-04-23)
 *
 * Used as:
 *   1. CI test input for the exporter — exercises codeBlock, blockquote,
 *      horizontalRule, image, footnote, and anchor
 *   2. Prompt example for the LLM document generator (research report style)
 */
export const reportExample: DocumentAst = {
  // ──────────────────────────────────────────────
  // Meta
  // ──────────────────────────────────────────────
  meta: {
    title: "Empirical Performance of NQRust-HV vs Java Monolith Migrations",
    subtitle: "Internal R&D Benchmark Report — Cycle Q1-2026",
    author: "Dr. Aryan Kusuma",
    organization: "NQ Technology R&D",
    date: "2026-03-15",
    pageSize: "letter",
    showPageNumbers: false,
    font: "Arial",
    fontSize: 12,
  },

  // ──────────────────────────────────────────────
  // Cover page
  // ──────────────────────────────────────────────
  coverPage: {
    title: "Empirical Performance of NQRust-HV vs Java Monolith Migrations",
    subtitle: "Internal R&D Benchmark Report — Cycle Q1-2026",
    author: "Dr. Aryan Kusuma, R&D Team Lead",
    date: "2026-03-15",
    organization: "NQ Technology R&D",
  },

  // No header / footer — intentionally distinct from proposal fixture.

  // ──────────────────────────────────────────────
  // Body
  // ──────────────────────────────────────────────
  body: [
    // ── H1 title ──────────────────────────────────
    {
      type: "heading",
      level: 1,
      bookmarkId: "report-top",
      children: [
        {
          type: "text",
          text: "Empirical Performance of NQRust-HV vs Java Monolith Migrations",
          bold: true,
        },
      ],
    },

    // ── Abstract ──────────────────────────────────
    {
      type: "heading",
      level: 2,
      bookmarkId: "abstract",
      children: [{ type: "text", text: "Abstract" }],
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "This report presents a controlled empirical study comparing the runtime performance of NQRust-HV — NQ Technology's Rust-based high-velocity service framework — against equivalent Java monolith baselines across 18 production-representative workloads. ",
        },
        {
          type: "text",
          text: "We measured p50, p95, and p99 tail latency, sustained throughput (req/s), and heap allocation rate over 72-hour soak runs. ",
        },
        {
          type: "text",
          text: "Across all workloads, NQRust-HV achieved a median p95 latency reduction from 420 ms to 110 ms (Cohen's d = 1.42, p < 0.001) and a 3.8× throughput increase at equivalent CPU budget.",
        },
        {
          type: "footnote",
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  text: "Statistical significance was assessed using Welch's two-tailed t-test with α = 0.01, after confirming non-normality via the Shapiro-Wilk test (W < 0.92 for all latency distributions). Effect sizes reported as Cohen's d; d > 0.8 is considered large.",
                },
              ],
            },
          ],
        },
        {
          type: "text",
          text: " Heap allocation rates dropped by 91 %, eliminating GC pause spikes that had been the primary source of p99 variance in the Java baseline.",
        },
      ],
    },

    // ── Methodology ───────────────────────────────
    {
      type: "heading",
      level: 2,
      bookmarkId: "methodology",
      children: [{ type: "text", text: "Methodology" }],
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "Each workload was replicated from a staging clone of a client production environment. Traffic was generated by a deterministic Locust harness that replayed 30 days of real request logs at 1× and 5× peak rates. Both the Java baseline (Spring Boot 3.2, JVM 21, G1GC) and the NQRust-HV target (v0.14.3, Tokio async runtime, jemalloc) were deployed on identical bare-metal nodes (32-core AMD EPYC 7543, 128 GB RAM, NVMe) to eliminate hypervisor jitter. The benchmark driver below encapsulates the core measurement loop:",
        },
      ],
    },
    {
      type: "codeBlock",
      language: "python",
      code: `import time, statistics, requests, concurrent.futures

ENDPOINTS = {
    "java":    "http://java-baseline:8080/api/process",
    "nqrust":  "http://nqrust-hv:9000/api/process",
}
PAYLOAD   = open("fixtures/request_p95.json").read().encode()
WARMUP_S  = 30
MEASURE_S = 300
CONCUR    = 64

def latency_sample(url: str) -> float:
    t0 = time.perf_counter()
    requests.post(url, data=PAYLOAD, timeout=5)
    return (time.perf_counter() - t0) * 1000  # ms

def run_bench(name: str, url: str) -> dict:
    samples: list[float] = []
    deadline = time.time() + WARMUP_S + MEASURE_S
    with concurrent.futures.ThreadPoolExecutor(max_workers=CONCUR) as pool:
        futs = [pool.submit(latency_sample, url) for _ in range(10_000)]
        for f in concurrent.futures.as_completed(futs):
            if time.time() > time.time() - WARMUP_S:
                samples.append(f.result())
    samples.sort()
    n = len(samples)
    return {
        "runtime": name,
        "p50_ms":  samples[int(n * 0.50)],
        "p95_ms":  samples[int(n * 0.95)],
        "p99_ms":  samples[int(n * 0.99)],
        "stddev":  statistics.stdev(samples),
    }

results = [run_bench(k, v) for k, v in ENDPOINTS.items()]`,
    },
    {
      type: "mermaid",
      code: `flowchart LR
  Data["Raw data"] --> Clean["Clean + validate"]
  Clean --> Model["Fit model"]
  Model --> Eval["Evaluate"]
  Eval --> Report["Publish report"]`,
      caption: "Methodology pipeline",
    },
    {
      type: "chart",
      chart: {
        type: "bar",
        title: "Experiment results by cohort",
        data: [
          { label: "Cohort A", value: 74 },
          { label: "Cohort B", value: 82 },
          { label: "Cohort C", value: 91 },
        ],
      },
      caption: "Accuracy (%) by cohort",
    },

    // ── Results ───────────────────────────────────
    {
      type: "heading",
      level: 2,
      bookmarkId: "results",
      children: [{ type: "text", text: "Results" }],
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "Table 1 below summarises the aggregate latency metrics. Across 18 workloads (each run at 1× and 5× peak, totalling 36 measurement runs per system), NQRust-HV consistently outperformed the Java baseline on every percentile. The most dramatic improvement appeared at p99: the Java baseline exhibited GC pause spikes reaching 1,840 ms at 5× load, while NQRust-HV's p99 remained at 210 ms — an 8.8× reduction. Throughput at iso-latency budget (p95 ≤ 200 ms) improved from 4,200 req/s to 16,100 req/s.",
        },
      ],
    },
    {
      type: "horizontalRule",
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "Memory utilisation tells a complementary story. The Java baseline's resident set size (RSS) grew from 3.1 GB at steady state to 7.8 GB after 72 hours of soak testing, consistent with slow off-heap accumulation in third-party JDBC driver internals. NQRust-HV's RSS remained stable at 680 MB ± 12 MB throughout. CPU utilisation at equivalent request rates was 38 % lower for NQRust-HV, attributable primarily to the elimination of JIT compilation overhead and reduced context-switch frequency from the cooperative Tokio task model.",
        },
      ],
    },

    // ── Chart image ───────────────────────────────
    {
      type: "image",
      src: "unsplash:benchmark chart",
      alt: "Aggregated latency p95 across 12 benchmarks",
      width: 600,
      height: 400,
      caption: "Figure 1. Throughput × latency across workloads. Error bars show ±1 standard deviation across 5 repeated runs.",
      align: "center",
    },

    // ── Findings ──────────────────────────────────
    {
      type: "heading",
      level: 2,
      bookmarkId: "findings",
      children: [{ type: "text", text: "Findings" }],
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "The following four principal findings emerge from the data and are considered actionable for migration planning:",
        },
      ],
    },
    {
      type: "list",
      ordered: true,
      startAt: 1,
      items: [
        {
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  text: "NQRust-HV reduces p95 tail latency by 73.8 % (from 420 ms to 110 ms) and p99 tail latency by 88.6 % (from 1,840 ms to 210 ms) relative to the Spring Boot 3.2 baseline under equivalent 5× peak load.",
                },
              ],
            },
          ],
        },
        {
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  text: "Throughput at iso-latency budget (p95 ≤ 200 ms) improves 3.8× (4,200 → 16,100 req/s) with no additional hardware provisioning, providing a direct cost-reduction pathway for workloads that are currently latency-constrained.",
                },
              ],
            },
          ],
        },
        {
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  text: "Heap allocation rate drops from 2.4 GB/s to 210 MB/s (−91 %), eliminating all GC pause spikes observed in the Java baseline and reducing RSS growth from 4.7 GB over 72 hours to under 15 MB.",
                },
              ],
            },
          ],
        },
        {
          children: [
            {
              type: "paragraph",
              children: [
                {
                  type: "text",
                  text: "The NQRust-HV migration path is incremental: the Tokio-based async gateway accepts HTTP/1.1, HTTP/2, and gRPC simultaneously, enabling workload-by-workload cutover with zero downtime and automatic rollback via feature flags.",
                },
              ],
            },
          ],
        },
      ],
    },

    // ── Conclusions ───────────────────────────────
    {
      type: "heading",
      level: 2,
      bookmarkId: "conclusions",
      children: [{ type: "text", text: "Conclusions" }],
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "The empirical evidence strongly supports migrating client-facing, latency-sensitive services from the Java monolith baseline to NQRust-HV. The performance gains are large in both absolute and effect-size terms, reproducible across workload types (OLTP, batch-analytics, streaming, and webhook-dispatch), and stable over 72-hour soak runs. We recommend proceeding to the phased migration plan outlined in the accompanying Infrastructure Migration Proposal (PROP/NQT/2026/001). The migration should prioritise the three highest-traffic service clusters first, targeting a 6-month delivery horizon with monthly measurement checkpoints using the benchmark harness published in this report.",
        },
      ],
    },
    {
      type: "blockquote",
      attribution: "John Ousterhout, A Philosophy of Software Design (2018), §2.3",
      children: [
        {
          type: "paragraph",
          children: [
            {
              type: "text",
              text: "Complexity is anything related to the structure of a software system that makes it hard to understand and modify. Complexity can take many forms … if a system is hard to understand and modify, it is complex. Performance is not the same as simplicity, but systems that eliminate unnecessary abstraction layers tend to achieve both.",
              italic: true,
            },
          ],
        },
      ],
    },
    {
      type: "paragraph",
      children: [
        {
          type: "text",
          text: "Return to ",
        },
        {
          type: "anchor",
          bookmarkId: "abstract",
          children: [
            {
              type: "text",
              text: "Abstract",
              underline: true,
              color: "#1155CC",
            },
          ],
        },
        {
          type: "text",
          text: " for a summary of statistical methodology, or consult the benchmark harness source in the Methodology section for reproduction details.",
        },
      ],
    },
  ],
}
